<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark min-vh-100">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100 position-fixed">
                <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                    <span class="fs-5 d-none d-sm-inline">Menu</span>
                </a>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li class="nav-item">
                        <a href="<?php echo $this->url->get(VIEW_PATH) ?>" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-house" style="color: #1c5ece;"></i> <span class="ms-1 d-none d-sm-inline">Accueil</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url->get(VIEW_PATH."/collaborateur") ?>" class="nav-link align-middle px-0">
                            <i class="fa-solid fa-users" style="color: #1c5ece;"></i> <span class="ms-1 d-none d-sm-inline">Collaborateurs</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url->get(VIEW_PATH."/client") ?>" class="nav-link align-middle px-0">
                        <i class="fa-solid fa-users" style="color: #1c5ece;"></i> <span class="ms-1 d-none d-sm-inline">Clients</span>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $this->url->get(VIEW_PATH."/equipe") ?>" class="nav-link align-middle px-0">
                        <i class="fa-solid fa-users" style="color: #1c5ece;"></i> <span class="ms-1 d-none d-sm-inline">Equipes</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="container">
            <?php if ($this->flashSession->has('error')) : ?>
                <?php $errorMessages = $this->flashSession->getMessages('error'); ?>
                <?php foreach ($errorMessages as $errorMessage) : ?>
                    <div class='alert alert-danger mt-2'><?php echo $errorMessage ?></div>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php echo $this->getContent(); ?>
        </div>
    </div>
</div>