<?php $this->assets->outputJs(); ?>

<div class="page-header">
    <h1>Equipes</h1>
</div>

<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createEquipeModal">
    Créer équipe
</button>

<div class="modal" tabindex="-1" id="createEquipeModal" aria-labelledby="createEquipeModal" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Création d'une équipe</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" action="<?= $this->url->get(VIEW_PATH."/equipe/createEquipe") ?>">
                    <?php foreach ($this->view->create as $element) : ?>
                        <div>
                            <?php if ($element->getName() != 'Valider') :?>
                                <label for="<?= $element->getName() ?>"><?= $element->label() ?></label>
                            <?php endif; ?>
                            <?= $element->render() ?>
                        </div>
                    <?php endforeach; ?>
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div> <?php echo $this->view->equipe ?></div>

<script>
    deleteButtons = document.getElementsByName('deleteEquipe');
    Array.from(deleteButtons).forEach((button) => {
        button.addEventListener("click", function() {
            let form = document.createElement('form')
            form.method = "post"
            form.action = "equipe/deleteEquipe"
            form.id = "formDeleteEquipe"
            let hiddenIdInput = document.createElement('input')
            hiddenIdInput.type = 'hidden'
            hiddenIdInput.name = "idEquipe"
            hiddenIdInput.value = button.dataset['id']
            let confirmInput = document.createElement('input')
            confirmInput.className = "btn btn-success me-2 mt-4"
            confirmInput.type = "submit"
            confirmInput.value = "confirmer"
            let stopInput = document.createElement('button')
            stopInput.className = "btn btn-danger mt-4"
            stopInput.type = "button"
            stopInput.textContent = "Annuler"
            stopInput.addEventListener("click", function() {
                document.getElementById("formDeleteEquipe").remove()
            })

            form.append(hiddenIdInput)
            form.append(confirmInput)
            form.append(stopInput)

            button.parentNode.append(form)

        })
    })
</script>